@server=http://localhost:3000

###
POST {{server}}/api/v1/trello
Content-Type: application/json

{
    "type": "issue",
    "title": "nada",
    "description": "asdas"
}

###
POST {{server}}/api/v1/trello
Content-Type: application/json

{
    "type": "bug",
    "title": "nada",
    "description": "asdas"
}

###
POST {{server}}/api/v1/trello
Content-Type: application/json

{
    "type": "task",
    "title": "NAdando",
    "category": "Maintenance"
}

###
POST {{server}}/api/v1/trello
Content-Type: application/json

{
    "type": "task",
    "title": "NAda",
    "category": "Maintenance"
}


###
PATCH {{server}}/api/v1/trello/prepare


